language: node_js
node_js:
- "stable"
cache:
  directories:
  - node_modules
install:
- npm install -g codecov
- npm install
script:
- npm test
- npm run build
- npm run coverage
on:
  branch: master
